### ISSUE TITLE
Feature: able to use synonym using fonts name

### ISSUE THREAD

**Issue by wishtrip-dev** [rwbutler/TypographyKit#3]
Motivation: 
In a project, might have 7 basic font size like: title1, title2, title3, body etc.
I would like to define **logical** fonts name that will "inherit" the basic font. 
like:
button -> title2 + blackColor
imageCaptions -> body + other feature

Suggestion:
"title2": {
            "font-name": "NotoSans-Regular",
            "point-size":19,
            "text-color": "white"
        },
"button": { 
             "basedOn":"title2",
            "text-color": "yellow"
        },

**Comment by rwbutler** [comment]
Thanks for the suggestion - we've actually been thinking about adding something like this too - I'll look into this shortly and get back to you.

**Comment by rwbutler** [comment]
I've just implemented this in 1.1.3 - there's a section added to the README called Extending Styles 👍🏻
