### ISSUE TITLE
Setting preferredContentSizeCategory in app

### ISSUE THREAD

**Issue by icedice** [rwbutler/TypographyKit#8]
Im looking into using TypographyKit and I looks very promising to get our typography organised, right now it's a mess. 

One thing I'm not sure how to do though is this:

We need our end-users to be able to se the preferredContentSizeCategory directly in the app (hence overriding the setting from Settings.app) og choose the not override and just go with their system setting.  

I did a quick test with TypographyKit where I am setting the overriding preferredContentSizeCategory by subclassing UIApplication like so:

```
class App: UIApplication{
    
    var customSize: UIContentSizeCategory?
    
    override var preferredContentSizeCategory: UIContentSizeCategory{
        return size ?? super.preferredContentSizeCategory
    }
    
}
```

This does kinda work, but I was unable to get TypographyKit to refresh the sizes when setting customSize (with out persisting the setting and restarting the app). Is there a way to force TypographyKit to update all text but fetching the new UIContentSizeCategory? I tried calling TypographyKit.refresh() but this seems to fetch new configuration now apply the new UIContentSizeCategory.

Hopefully someone will be able to help with this as this is the last thing I'm missing to start using TypographyKit

**Comment by rwbutler** [comment]
When the preferredContentSizeCategory is updated in iOS, the operating system posts a `UIContentSizeCategory.didChangeNotification` notification. TypographyKit listens for this notification and updates the UI elements using the information contained within the notification's `userInfo` dictionary. Therefore if you post this notification when the user updates their `preferred ContentSizeCategory` then TypographyKit should refresh all UI elements to use the new `UIContentSizeCategory` e.g.

```swift
override var preferredContentSizeCategory: UIContentSizeCategory{
        let newContentSizeCategory = size ?? super.preferredContentSizeCategory
        NotificationCenter.default.post(name: UIContentSizeCategory.didChangeNotification, object: nil, userInfo: [UIContentSizeCategory.newValueUserInfoKey: newContentSizeCategory])
    }

```

Hope this helps!

**Comment by icedice** [comment]
Hi rwbutler and thank you for the input. I don't know why I did not think of posting that event..  Anyways, I'm still not able to get it to work. I created a tiny example which I guess should work but nothing happens (until I change the preferredContentSizeCategory in the phone settings) Do you agree that this should work:

```
import UIKit
import TypographyKit

extension UIFont.TextStyle
{
    static let heading = UIFont.TextStyle(rawValue: "heading")
}

class ViewController: UIViewController {
    
    @IBOutlet weak var label: UILabel!
    override func viewDidLoad() {
        super.viewDidLoad()
        
        label.text("John was here", style: .heading)
    }
    
    @IBAction func updateTapped(_ sender: Any) {
        NotificationCenter.default.post(name: UIContentSizeCategory.didChangeNotification, object: nil, userInfo: [UIContentSizeCategory.newValueUserInfoKey: UIContentSizeCategory.accessibilityExtraExtraExtraLarge])
    }
}

// TypographyKit.json
//{
//     "ui-font-text-styles": {
//         "heading": {
//            "font-name": "Avenir-Medium",
//            "point-size": 36,
//            "text-color": "text",
//            "letter-case": "regular"
//        }
//    }
//}

```
I have validated that the notification is send and I am able to receive it and extract the UIContentSizeCategory, but the label does not update.

**Comment by rwbutler** [comment]
I'll take a look and get back to you shortly!

**Comment by rwbutler** [comment]
I've had a look at this and found that the reason why the change in text size isn't being applied is because the font is being scaled using `UIFontMetrics` applying the default `UIContentSizeCategory`. It's possible to work around this by changing the scaling mode used by TypographyKit to stepping either by programmatically:

```swift
TypographyKit.scalingMode = .stepping
```

Or in config using:

```json
"scaling-mode": "stepping"
```

However, if you're willing to update I've just released 4.2.0 which passes the new `UIContentSizeCategory` to `UIFontMetrics` meaning that everything should 'just work' as is - hope this helps!

**Comment by icedice** [comment]
Thank you for your time! I will try this out tomorrow. As I'm only just starting out with TypographyKit I will just try updating to 4.2.0 and see if it fixes it.

**Comment by icedice** [comment]
I could not wait testing it out :) A quick test shows that updating to 4.2.0 solves the issue perfectly. Thanks a lot for the very quick help.

**Comment by rwbutler** [comment]
No problem - glad that worked for you! 😃
